// Code generated by generator; DO NOT EDIT.
package goesdsl

// SetLang 设置 Lang: Specifies the language the script is written in. Defaults to painless.
func (s *Script) SetLang(v string) *Script {
	if s == nil {
		return s
	}
	s.lang = v
	return s
}

// SetSource 设置 Source: The script itself, which you specify as source for an inline script or id for a stored script.
func (s *Script) SetSource(v string) *Script {
	if s == nil {
		return s
	}
	s.source = v
	return s
}

// SetParams 设置 Params: Specifies any named parameters that are passed into the script as variables.
func (s *Script) SetParams(v map[string]any) *Script {
	if s == nil {
		return s
	}
	s.params = v
	return s
}

// AddParams 追加 Params: Specifies any named parameters that are passed into the script as variables.
func (s *Script) AddParams(k string, v any) *Script {
	if s == nil {
		return s
	}
	if s.params == nil {
		s.params = make(map[string]any)
	}
	s.params[k] = v
	return s
}
