// Code generated by generator; DO NOT EDIT.
package goesdsl

// NewTermLevelQueriesExist
func NewTermLevelQueriesExist(field string) *TermLevelQueriesExist {
	s := &TermLevelQueriesExist{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesExist) SetField(v string) *TermLevelQueriesExist {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// NewTermLevelQueriesFuzzy
func NewTermLevelQueriesFuzzy(field string) *TermLevelQueriesFuzzy {
	s := &TermLevelQueriesFuzzy{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesFuzzy) SetField(v string) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesFuzzy) SetValue(v string) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// SetFuzziness
func (s *TermLevelQueriesFuzzy) SetFuzziness(v string) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.fuzziness = v
	return s
}

// SetMaxExpansions
func (s *TermLevelQueriesFuzzy) SetMaxExpansions(v int32) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.maxExpansions = &v
	return s
}

// SetPrefixLength
func (s *TermLevelQueriesFuzzy) SetPrefixLength(v int32) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.prefixLength = &v
	return s
}

// SetTranspositions
func (s *TermLevelQueriesFuzzy) SetTranspositions(v bool) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.transpositions = &v
	return s
}

// SetRewrite
func (s *TermLevelQueriesFuzzy) SetRewrite(v string) *TermLevelQueriesFuzzy {
	if s == nil {
		return s
	}
	s.rewrite = v
	return s
}

// NewTermLevelQueriesIDs
func NewTermLevelQueriesIDs() *TermLevelQueriesIDs {
	s := &TermLevelQueriesIDs{}
	return s
}

// SetValues
func (s *TermLevelQueriesIDs) SetValues(v ...string) *TermLevelQueriesIDs {
	if s == nil {
		return s
	}
	s.values = v
	return s
}

// AddValues
func (s *TermLevelQueriesIDs) AddValues(v ...string) *TermLevelQueriesIDs {
	if s == nil {
		return s
	}
	if len(v) > 0 {
		s.values = append(s.values, v...)
	}
	return s
}
// NewTermLevelQueriesPrefix
func NewTermLevelQueriesPrefix(field string) *TermLevelQueriesPrefix {
	s := &TermLevelQueriesPrefix{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesPrefix) SetField(v string) *TermLevelQueriesPrefix {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesPrefix) SetValue(v string) *TermLevelQueriesPrefix {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// SetRewrite
func (s *TermLevelQueriesPrefix) SetRewrite(v string) *TermLevelQueriesPrefix {
	if s == nil {
		return s
	}
	s.rewrite = v
	return s
}

// SetCaseInsensitive
func (s *TermLevelQueriesPrefix) SetCaseInsensitive(v bool) *TermLevelQueriesPrefix {
	if s == nil {
		return s
	}
	s.caseInsensitive = &v
	return s
}

// NewTermLevelQueriesRange
func NewTermLevelQueriesRange(field string) *TermLevelQueriesRange {
	s := &TermLevelQueriesRange{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesRange) SetField(v string) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetGt
func (s *TermLevelQueriesRange) SetGt(v any) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.gt = v
	return s
}

// SetGte
func (s *TermLevelQueriesRange) SetGte(v any) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.gte = v
	return s
}

// SetLt
func (s *TermLevelQueriesRange) SetLt(v any) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.lt = v
	return s
}

// SetLte
func (s *TermLevelQueriesRange) SetLte(v any) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.lte = v
	return s
}

// SetFormat
func (s *TermLevelQueriesRange) SetFormat(v string) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.format = v
	return s
}

// SetRelation
func (s *TermLevelQueriesRange) SetRelation(v string) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.relation = v
	return s
}

// SetTimeZone
func (s *TermLevelQueriesRange) SetTimeZone(v string) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.timeZone = v
	return s
}

// SetBoost
func (s *TermLevelQueriesRange) SetBoost(v float64) *TermLevelQueriesRange {
	if s == nil {
		return s
	}
	s.boost = &v
	return s
}

// NewTermLevelQueriesRegexp
func NewTermLevelQueriesRegexp(field string) *TermLevelQueriesRegexp {
	s := &TermLevelQueriesRegexp{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesRegexp) SetField(v string) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesRegexp) SetValue(v any) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// SetFlags
func (s *TermLevelQueriesRegexp) SetFlags(v string) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.flags = v
	return s
}

// SetCaseInsensitive
func (s *TermLevelQueriesRegexp) SetCaseInsensitive(v bool) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.caseInsensitive = &v
	return s
}

// SetMaxDeterminizedStates
func (s *TermLevelQueriesRegexp) SetMaxDeterminizedStates(v int64) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.maxDeterminizedStates = &v
	return s
}

// SetRewrite
func (s *TermLevelQueriesRegexp) SetRewrite(v string) *TermLevelQueriesRegexp {
	if s == nil {
		return s
	}
	s.rewrite = v
	return s
}

// NewTermLevelQueriesTerm
func NewTermLevelQueriesTerm(field string) *TermLevelQueriesTerm {
	s := &TermLevelQueriesTerm{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesTerm) SetField(v string) *TermLevelQueriesTerm {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesTerm) SetValue(v any) *TermLevelQueriesTerm {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// SetBoost
func (s *TermLevelQueriesTerm) SetBoost(v float64) *TermLevelQueriesTerm {
	if s == nil {
		return s
	}
	s.boost = &v
	return s
}

// SetCaseInsensitive
func (s *TermLevelQueriesTerm) SetCaseInsensitive(v bool) *TermLevelQueriesTerm {
	if s == nil {
		return s
	}
	s.caseInsensitive = &v
	return s
}

// NewTermLevelQueriesTerms
func NewTermLevelQueriesTerms(field string) *TermLevelQueriesTerms {
	s := &TermLevelQueriesTerms{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesTerms) SetField(v string) *TermLevelQueriesTerms {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesTerms) SetValue(v ...any) *TermLevelQueriesTerms {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// AddValue
func (s *TermLevelQueriesTerms) AddValue(v ...any) *TermLevelQueriesTerms {
	if s == nil {
		return s
	}
	if len(v) > 0 {
		s.value = append(s.value, v...)
	}
	return s
}
// SetBoost
func (s *TermLevelQueriesTerms) SetBoost(v float64) *TermLevelQueriesTerms {
	if s == nil {
		return s
	}
	s.boost = &v
	return s
}

// NewTermLevelQueriesTermsSet
func NewTermLevelQueriesTermsSet(field string) *TermLevelQueriesTermsSet {
	s := &TermLevelQueriesTermsSet{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesTermsSet) SetField(v string) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetTerms
func (s *TermLevelQueriesTermsSet) SetTerms(v ...any) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	s.terms = v
	return s
}

// AddTerms
func (s *TermLevelQueriesTermsSet) AddTerms(v ...any) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	if len(v) > 0 {
		s.terms = append(s.terms, v...)
	}
	return s
}
// SetMinimumShouldMatch
func (s *TermLevelQueriesTermsSet) SetMinimumShouldMatch(v float64) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	s.minimumShouldMatch = &v
	return s
}

// SetMinimumShouldMatchField
func (s *TermLevelQueriesTermsSet) SetMinimumShouldMatchField(v string) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	s.minimumShouldMatchField = v
	return s
}

// SetMinimumShouldMatchScript
func (s *TermLevelQueriesTermsSet) SetMinimumShouldMatchScript(v Script) *TermLevelQueriesTermsSet {
	if s == nil {
		return s
	}
	s.minimumShouldMatchScript = &v
	return s
}

// NewTermLevelQueriesWildcard
func NewTermLevelQueriesWildcard(field string) *TermLevelQueriesWildcard {
	s := &TermLevelQueriesWildcard{}
	s.field = field
	return s
}

// SetField
func (s *TermLevelQueriesWildcard) SetField(v string) *TermLevelQueriesWildcard {
	if s == nil {
		return s
	}
	s.field = v
	return s
}

// SetValue
func (s *TermLevelQueriesWildcard) SetValue(v string) *TermLevelQueriesWildcard {
	if s == nil {
		return s
	}
	s.value = v
	return s
}

// SetBoost
func (s *TermLevelQueriesWildcard) SetBoost(v float64) *TermLevelQueriesWildcard {
	if s == nil {
		return s
	}
	s.boost = &v
	return s
}

// SetCaseInsensitive
func (s *TermLevelQueriesWildcard) SetCaseInsensitive(v bool) *TermLevelQueriesWildcard {
	if s == nil {
		return s
	}
	s.caseInsensitive = &v
	return s
}

// SetRewrite
func (s *TermLevelQueriesWildcard) SetRewrite(v string) *TermLevelQueriesWildcard {
	if s == nil {
		return s
	}
	s.rewrite = v
	return s
}

